POST {{host}}/api/v1/short_links
Content-Type: application/json

{
  "originalLinkUrl": "https://stepniewski.tech/blog/post/4-linkshortener-with-akka-concept/",
  "tags": ["test", "v1"]
}

###

GET {{host}}/api/v1/short_links/XFw7cU6b